/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RazonesFinancieras.java
 *
 * Created on 29/11/2009, 07:08:24 PM
 */

package razones;

import cuentas.*;

/**
 *
 * @author Gabriel
 */
public class RazonesFinancieras extends FenomenosEconomicos {

    /** Creates new form RazonesFinancieras */
    public RazonesFinancieras(Activo activo, Pasivo pasivo, Capital capital, Otras otras) {
        initComponents();
        this.setLocation(450,150);
        if( activo.saldo() != 0 && pasivo.saldo() != 0 &&
            capital.saldo() != 0 && otras.saldo() != 0 ){
            campo.setValueAt(liquidez( activo, pasivo ), 0, 1);
            campo.setValueAt(solvencia( activo, pasivo ), 1, 1);
            campo.setValueAt(estabilidad( activo, pasivo ), 2, 1);
            campo.setValueAt(inmovilizacion( activo, capital ), 3, 1);
            campo.setValueAt(rentabilidadVentas( otras ), 4, 1);
            campo.setValueAt(rentabilidadInversion( capital, otras ), 5, 1);
            this.toFront();
            this.setVisible(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        campo = new javax.swing.JTable();

        setClosable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(finanzas.FinanzasApp.class).getContext().getResourceMap(RazonesFinancieras.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        campo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Liquidez", null},
                {"Solvencia", null},
                {"Estabilidad", null},
                {"Inmovilización", null},
                {"Rentabilidad en Ventas", null},
                {"Rentabilidad en Inversión", null}
            },
            new String [] {
                "Fenómeno Económico", "Razones Financieras"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        campo.setName("campo"); // NOI18N
        jScrollPane1.setViewportView(campo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable campo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
