/*
 * FinanzasView.java
 */

package finanzas;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import trabajo.AreaDeTrabajo;

/**
 * The application's main frame.
 */
public class FinanzasView extends FrameView {

    public FinanzasView(SingleFrameApplication app) {
        super(app);        
        initComponents();
        estadoFinanciero.setVisible(false);

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = FinanzasApp.getApplication().getMainFrame();
            aboutBox = new FinanzasAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        FinanzasApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pane = new javax.swing.JDesktopPane();
        estadoFinanciero = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox();
        abrirEstado = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu menuArchivo = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        nuevoTrabajo = new javax.swing.JMenuItem();
        javax.swing.JMenuItem salir = new javax.swing.JMenuItem();
        javax.swing.JMenu menuAyuda = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(finanzas.FinanzasApp.class).getContext().getResourceMap(FinanzasView.class);
        pane.setBackground(resourceMap.getColor("pane.background")); // NOI18N
        pane.setName("pane"); // NOI18N

        estadoFinanciero.setClosable(true);
        estadoFinanciero.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        estadoFinanciero.setTitle(resourceMap.getString("estadoFinanciero.title")); // NOI18N
        estadoFinanciero.setName("estadoFinanciero"); // NOI18N
        estadoFinanciero.setVisible(true);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Consultores Asociados S.A.", "Cinépolis S.A." }));
        estado.setName("estado"); // NOI18N

        abrirEstado.setText(resourceMap.getString("abrirEstado.text")); // NOI18N
        abrirEstado.setName("abrirEstado"); // NOI18N
        abrirEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout estadoFinancieroLayout = new javax.swing.GroupLayout(estadoFinanciero.getContentPane());
        estadoFinanciero.getContentPane().setLayout(estadoFinancieroLayout);
        estadoFinancieroLayout.setHorizontalGroup(
            estadoFinancieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadoFinancieroLayout.createSequentialGroup()
                .addGroup(estadoFinancieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(estadoFinancieroLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(estadoFinancieroLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(abrirEstado)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        estadoFinancieroLayout.setVerticalGroup(
            estadoFinancieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadoFinancieroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(estadoFinancieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(abrirEstado)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        estadoFinanciero.setBounds(20, 20, 330, 150);
        pane.add(estadoFinanciero, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        menuArchivo.setText(resourceMap.getString("menuArchivo.text")); // NOI18N
        menuArchivo.setName("menuArchivo"); // NOI18N

        abrir.setText(resourceMap.getString("abrir.text")); // NOI18N
        abrir.setName("abrir"); // NOI18N
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        menuArchivo.add(abrir);

        nuevoTrabajo.setText(resourceMap.getString("nuevoTrabajo.text")); // NOI18N
        nuevoTrabajo.setName("nuevoTrabajo"); // NOI18N
        nuevoTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoTrabajoActionPerformed(evt);
            }
        });
        menuArchivo.add(nuevoTrabajo);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(finanzas.FinanzasApp.class).getContext().getActionMap(FinanzasView.class, this);
        salir.setAction(actionMap.get("quit")); // NOI18N
        salir.setText(resourceMap.getString("salir.text")); // NOI18N
        salir.setName("salir"); // NOI18N
        menuArchivo.add(salir);

        menuBar.add(menuArchivo);

        menuAyuda.setText(resourceMap.getString("menuAyuda.text")); // NOI18N
        menuAyuda.setName("menuAyuda"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        menuAyuda.add(aboutMenuItem);

        menuBar.add(menuAyuda);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoTrabajoActionPerformed
        if( indice < 10 ){
           areas[indice] = new AreaDeTrabajo(-1);
           pane.add(areas[indice]);
           areas[indice].setVisible(true);
           indice++;
        }

    }//GEN-LAST:event_nuevoTrabajoActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        estadoFinanciero.setLocation(500,100);
        estadoFinanciero.setVisible(true);
    }//GEN-LAST:event_abrirActionPerformed

    private void abrirEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirEstadoActionPerformed
        areas[indice] = new AreaDeTrabajo(estado.getSelectedIndex());
        pane.add(areas[indice]);
        estadoFinanciero.setVisible(false);
        areas[indice].setVisible(true);
        areas[indice].inicio(estado.getSelectedIndex());
        indice++;
    }//GEN-LAST:event_abrirEstadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JButton abrirEstado;
    private javax.swing.JComboBox estado;
    private javax.swing.JInternalFrame estadoFinanciero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem nuevoTrabajo;
    private javax.swing.JDesktopPane pane;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private AreaDeTrabajo areas[] = new AreaDeTrabajo[10];
    private static int indice = 0;
    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
