/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PuntoEquilibrio.java
 *
 * Created on 29/11/2009, 08:06:34 PM
 */

package calculos;

import cuentas.Otras;

/**
 *
 * @author Gabriel
 */
public class PuntoEquilibrio extends javax.swing.JInternalFrame {
    private Otras otras;

    /** Creates new form PuntoEquilibrio */
    public PuntoEquilibrio( Otras otras, int index ) {
        initComponents();
        this.otras = otras;
        switch( index ){
            case 0:
                precio.setValueAt(25000, 0, 0);
                break;
            case 1:
                precio.setValueAt(200, 0, 0);
                break;
        }
        
        this.setLocation(470, 100);
        this.toFront();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        campo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        precio = new javax.swing.JTable();
        calcular = new javax.swing.JButton();

        setClosable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(finanzas.FinanzasApp.class).getContext().getResourceMap(PuntoEquilibrio.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        campo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Ventas", null},
                {"Número de Unidades", null},
                {"Costo Variable Total", null}
            },
            new String [] {
                "Datos", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        campo.setName("campo"); // NOI18N
        jScrollPane1.setViewportView(campo);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        precio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {new Double(1.0)}
            },
            new String [] {
                "Precio Promedio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        precio.setName("precio"); // NOI18N
        jScrollPane2.setViewportView(precio);

        calcular.setText(resourceMap.getString("calcular.text")); // NOI18N
        calcular.setName("calcular"); // NOI18N
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(calcular)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(calcular)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        double pe, por, p;
        p = Double.parseDouble(precio.getValueAt(0,0).toString());
        por = p * (otras.getCuenta("Costo de Ventas").saldo()/otras.getCuenta("Ventas").saldo());
        pe = otras.gastosDeOperacion()/(1-(por/p));

        campo.setValueAt(pe, 0, 1);
        campo.setValueAt(pe/p, 1, 1);
        campo.setValueAt((pe/p)*por, 2, 1);
    }//GEN-LAST:event_calcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JTable campo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable precio;
    // End of variables declaration//GEN-END:variables

}
