/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EstadoDiferencias.java
 *
 * Created on 29/11/2009, 04:09:56 PM
 */

package estados;

import cuentas.Otras;

/**
 *
 * @author Gabriel
 */
public class EstadoDiferencias extends Estado {

    /** Creates new form EstadoDiferencias */
    public EstadoDiferencias( Otras o1, Otras o2, String e, String a1, String a2 ) {
       initComponents();
        this.setLocation(280, 50);

        if( o1.utilidadNeta() != 0 && o2.utilidadNeta() != 0 ) {
            String txt = "";

            for( int i = 0; i < 41-(e.length()/2); i++ ) txt += " ";
            txt += e + "\n";

            String titulo = "Estado de Resultados Comparativo";
            for( int i = 0; i < 41-(titulo.length()/2); i++ ) txt += " ";
            txt += titulo + "\n\n";

            txt += "     " + titulo(0) + "      " + a1 + "     " + "      " + a2 + "     " + "  Diferencias  " + "\n";
            double v1 = o1.getCuenta("Ventas").saldo();
            double c1 = o1.getCuenta("Costo de Ventas").saldo();
            double b1 = o1.utilidadBruta();
            double q1 = o1.getCuenta("Gastos de Operacion").saldo();
            double u1 = o1.utilidadDeOperacion();
            double v2 = o2.getCuenta("Ventas").saldo();
            double c2 = o2.getCuenta("Costo de Ventas").saldo();
            double b2 = o2.utilidadBruta();
            double q2 = o2.getCuenta("Gastos de Operacion").saldo();
            double u2 = o2.utilidadDeOperacion();

            txt += "     " + titulo(3) + "$" + valor(v1) + "$" + valor(v2) + diferencias(v1,v2) + "\n";
            txt += "     " + titulo(1) + " " + "\n";
            txt += "     " + titulo(4) + " " + valor(c1) + " " + valor(c2) + diferencias(c1,c2) + "\n";
            txt += "     " + titulo(0) + " " + espacios(3)  + "\n";
            txt += "     " + titulo(5) + " " + valor(b1) + " " + valor(b2) + diferencias(b1,b2) + "\n";
            txt += "     " + titulo(1) + " " + "\n";
            txt += "     " + titulo(6) + " " + valor(q1) + " " + valor(q2) + diferencias(q1,q2) + "\n";

            double og1 = o1.getCuenta("Otros Gastos").saldo();
            double op1 = o1.getCuenta("Otros Productos").saldo();
            double og2 = o2.getCuenta("Otros Gastos").saldo();
            double op2 = o2.getCuenta("Otros Productos").saldo();

            if( (og1 != 0 && op1 != 0) || (og2 != 0 && op1 != 0) ){
                txt += "     " + titulo(0) + " " + espacios(3)  + "\n";
                txt += "     " + titulo(7) + " " + valor(u1) + " " + valor(u2) + diferencias(u1,u2) + "\n";
                txt += "     " + titulo(1) + "\n";
                txt += "     " + titulo(8) + " " + valor(og1) + " " + valor(og2) + diferencias(og1,og2) + "\n";
                txt += "     " + titulo(2) + "\n";
                txt += "     " + titulo(9) + " " + valor(op1) + " " + valor(op2) + diferencias(op1,op2) + "\n";
                txt += "     " + titulo(0) + " " + espacios(3)  + "\n";
            }else if( og1 != 0 || og2 != 0 ){
                txt += "     " + titulo(0) + " " + espacios(3)  + "\n";
                txt += "     " + titulo(7) + " " + valor(u1) + " " + valor(u2) + diferencias(u1,u2) + "\n";
                txt += "     " + titulo(1) + "\n";
                txt += "     " + titulo(8) + " " + valor(og1) + " " + valor(og2) + diferencias(og1,og2) + "\n";
                txt += "     " + titulo(0) + " " + espacios(3)   + "\n";
            }else if( op1 != 0 || op1 != 0 ){
                txt += "     " + titulo(0) + " " + espacios(3)  + "\n";
                txt += "     " + titulo(7) + " " + valor(u1) + " " + valor(u2) + diferencias(u1,u2) + "\n";
                txt += "     " + titulo(2) + "\n";
                txt += "     " + titulo(9) + " " + valor(op1) + " " + valor(op2) + diferencias(op1,op2) + "\n";
                txt += "     " + titulo(0) + " " + espacios(3)   + "\n";
            }

            double n1 = o1.utilidadNeta();
            double n2 = o2.utilidadNeta();

            txt += "     " + titulo(0)  + " " + espacios(3)   + "\n";
            txt += "     " + titulo(10) + "$" + valor(n1) + "$" + valor(n2) + diferencias(n1,n2) + "\n";

            estado.setText(txt);
            this.toFront();
            this.setVisible(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        estado = new javax.swing.JTextArea();

        setClosable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(finanzas.FinanzasApp.class).getContext().getResourceMap(EstadoDiferencias.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 350));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        estado.setColumns(20);
        estado.setEditable(false);
        estado.setRows(5);
        estado.setText(resourceMap.getString("estado.text")); // NOI18N
        estado.setName("estado"); // NOI18N
        jScrollPane1.setViewportView(estado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea estado;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
