/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EstadoPorcientos.java
 *
 * Created on 7/12/2009, 11:15:25 AM
 */

package estados;

import cuentas.Otras;

/**
 *
 * @author Gabriel
 */
public class EstadoPorcientos extends Estado {
    private Otras otras;

    /** Creates new form EstadoDiferencias */
    public EstadoPorcientos( Otras o, String e ) {
        initComponents();
        this.setLocation(280, 50);
        this.otras = o;

        if( o.utilidadNeta() != 0 ) {
            String txt = "";

            for( int i = 0; i < 41-(e.length()/2); i++ )
                txt += " ";
            txt += e + "\n";

            String titulo = "Estado de Resultados - Porcientos Integrados";
            for( int i = 0; i < 41-(titulo.length()/2); i++ )
                txt += " ";
            txt += titulo + "\n\n";

            double v = o.getCuenta("Ventas").saldo();
            double c = o.getCuenta("Costo de Ventas").saldo();
            double b = o.utilidadBruta();
            double q = o.getCuenta("Gastos de Operacion").saldo();
            double u = o.utilidadDeOperacion();

            txt += "\t    " + titulo(3) + "$" + valor(v) + " " + porcentaje(v) + "\n";
            txt += "\t    " + titulo(1) + " " + "\n";
            txt += "\t    " + titulo(4) + " " + valor(c) + " " + porcentaje(c) + "\n";
            txt += "\t    " + titulo(0) + " " + espacios(2)  + "\n";
            txt += "\t    " + titulo(5) + " " + valor(b) + " " + porcentaje(b) + "\n";
            txt += "\t    " + titulo(1) + " " + "\n";
            txt += "\t    " + titulo(6) + " " + valor(q) + " " + porcentaje(q) + "\n";

            double og = o.getCuenta("Otros Gastos").saldo();
            double op = o.getCuenta("Otros Productos").saldo();

            if( (og != 0 && op != 0) ){
                txt += "\t    " + titulo(0) + " " + espacios(2)  + "\n";
                txt += "\t    " + titulo(7) + " " + valor(u)  + " " + porcentaje(u)  + "\n";
                txt += "\t    " + titulo(1) + "\n";
                txt += "\t    " + titulo(8) + " " + valor(og) + " " + porcentaje(og) + "\n";
                txt += "\t    " + titulo(2) + "\n";
                txt += "\t    " + titulo(9) + " " + valor(op) + " " + porcentaje(op) + "\n";
            }else if( og != 0 ){
                txt += "\t    " + titulo(0) + " " + espacios(2)  + "\n";
                txt += "\t    " + titulo(7) + " " + valor(u)  + " " + porcentaje(u)  + "\n";
                txt += "\t    " + titulo(1) + "\n";
                txt += "\t    " + titulo(8) + " " + valor(og) + " " + porcentaje(og) + "\n";
            }else if( op != 0 ){
                txt += "\t    " + titulo(0) + " " + espacios(2)  + "\n";
                txt += "\t    " + titulo(7) + " " + valor(u)  + " " + porcentaje(u)  + "\n";
                txt += "\t    " + titulo(2) + "\n";
                txt += "\t    " + titulo(9) + " " + valor(op) + " " + porcentaje(op) + "\n";
            }

            double n = o.utilidadNeta();

            txt += "\t    " + titulo(0)  + " " + espacios(2) + "\n";
            txt += "\t    " + titulo(10) + "$" + valor(n) + " " + porcentaje(n) + "\n";

            estado.setText(txt);
            this.toFront();
            this.setVisible(true);
        }
    }

    public String porcentaje( double valor ){
        String aux = "";
        double porcentaje = (valor/otras.getSaldo("Ventas"))*100;
        aux += porcenToString(porcentaje) + "    ";
        return aux;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        estado = new javax.swing.JTextArea();

        setClosable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(finanzas.FinanzasApp.class).getContext().getResourceMap(EstadoPorcientos.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 350));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        estado.setColumns(20);
        estado.setEditable(false);
        estado.setRows(5);
        estado.setName("estado"); // NOI18N
        jScrollPane1.setViewportView(estado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea estado;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
